#!/usr/bin/env bash
# Installs Nginx

sudo apt-get update
sudo apt-get install -y nginx

sudo chown -R $(whoami) /etc/nginx/sites-available/
sudo chown -R $(whoami) /var/www/html/
sudo echo "Hello World!" > /var/www/html/index.html
sudo echo "server {
    listen 80;
    server_name _;

    location / {
    root /var/www/html;
    index index.html;
}
}" > /etc/nginx/sites-available/default
sudo service nginx start
