#!/usr/bin/env bash
# Installs Nginx

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80;
    server_name _;

    location / {
    root /var/www/html;
    index index.html;
}
}" > /etc/nginx/sites-available/default
service nginx start
