#!/usr/bin/env bash
# Installs nginx web server with configuration

apt-get update
apt-get install -y nginx

sudo 'chown -R $(whoami)' /etc/nginx/sites-available/
sudo 'chown -R $(whoami)' /var/www/html/

echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;

    location /redirect_me {
        return 301 https://google.com;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
