#!/usr/bin/env bash
# Installs nginx web server with configurations

apt-get update
apt-get install -y nginx
sudo chown -R $(whoami) /etc/nginx/sites-available/
sudo chown -R $(whoami) /var/www/html/

service nginx start
mkdir /etc/nginx/html

echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;

    location /redirect_me {
        return 301 https://google.com;
    }
    error_page 404 /404.html;
    location = /404.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
