#!/usr/bin/env bash
# Installs HAProxy with configurations as follows:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend akem.tech
    timeout client  30000
    bind 0:80
    default_backend akem.tech_backend

backend akem.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 316263-web-01 52.201.221.204:80 check
    server 316263-web-02 34.204.60.16:80 check
EOT

sudo service haproxy restart
