#!/usr/bin/env bash
# configures an nginx server to listen on port 80

# first creats a symbolic link (-s opt) between the nginx congig
# file and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx 
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -l)"
