#!/bin/bash

# Function that handles SIGTERM and SIGQUIT signals
cleanup_and_exit() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 1
}

# Function that handlesSIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Set up trap for SIGTERM and SIGQUIT signals
trap 'cleanup_and_exit' SIGTERM

# Set up trap for SIGINT signal
trap 'handle_sigint' SIGINT

# Get the script's PID and save it to the file /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
