#!/usr/bin/env bash
# Manages the script "manage_my_process".
#   When passed the argument `start`:
#       Starts manage_my_process
#       Creates a file containings its PID in /var/run/my_process.pid
#       Displays "manage_my_process started"
#   When passed the argument `stop`:
#       Stops manage_my_process
#       Deletes the file /var/run/my_process.pid
#       Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#       Stops manage_my_process
#       Deletes the file /var/run/my_process.pid
#       Starts manage_my_process
#       Creates a file containing its PID in /var/run/my_process.pid
#       Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#  +  "Usage: manage_my_process {start|stop|rest}

file=/var/run/my_process.pid
proc=manage_my_process
if [ "$1" = "start" ]; then
	./"$proc" & 
	echo "$!" > "$file"
	echo "$proc" started
elif [ "$1" = "stop" ]; then
	pkill -SIGKILL -f ./"$proc"
       	rm "$file"
	echo "$proc" stopped
elif [ "$1" = "restart" ]; then
	pkill -SIGKILL -f ./"$proc"
       	rm "$file"
	./"$proc" &
	echo "$!" > "$file"
	echo "$proc" restarted
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
