#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely with
# + a sleep 2 in between each iteration.
#   Display "I am invincible!!!" in between each iteration

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
