#!/bin/bash

# Check if a username argument is provided
if [ $# -ne 1 ]; then
	    echo "Usage: $0 <username>"
	        exit 1
fi

# Get the username from the argument
username="$1"

# Run the whoami command as the specified user
su - "$username" -c 'whoami'
