#!/usr/bin/env bash
#SSH client configuration settings
Host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCreation no
